#!/usr/bin/env node
/**
 * Zero-dependency build for dsh-free-models-hub.
 *
 *  - lib/core.js   <- src/core.js            (verbatim ESM)
 *  - lib/index.js  <- src/index.js           (verbatim ESM; imports ./core.js)
 *  - lib/client.cjs <- src/core.js + src/client/index.js
 *                    concatenated inside a lazy-CJS factory (`module.exports`),
 *                    the artifact format served at /plugins/<id>/client.js.
 *
 * Usage:
 *   node scripts/build.mjs           # write lib/
 *   node scripts/build.mjs --check   # verify lib/ matches sources (CI), exit 1 on drift
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = (p) => join(root, 'src', p)
const LIB = (p) => join(root, 'lib', p)

const BANNER = '// @generated by scripts/build.mjs — do not edit by hand.\n'

async function read(p) {
  return readFile(p, 'utf8')
}

/** Strip `export ` keywords so the file becomes plain declarations. */
function stripExports(source) {
  return source.replace(/^export\s+/gm, '')
}

/**
 * dsh-free-models-hub client bundle format (per @deepseek-ai/dsh-client-modules):
 * executing the served script must only REGISTER the factory via
 * `window.__ModuleLoader__.load({id, factory})`; all side effects live inside
 * the factory closure and run at materialization (factory(require) → exports).
 */
function buildClientBundle(coreSrc, clientSrc) {
  const body =
    `${stripExports(coreSrc)}\n` +
    `${stripExports(clientSrc)}\n` +
    `const __exports__ = { name: name, inject: inject, apply: apply };\n` +
    `if (module) { module.exports = __exports__; }\n` +
    `return __exports__;\n`
  return (
    `${BANNER}` +
    `window.__ModuleLoader__.load({\n` +
    `  id: 'dsh-free-models-hub',\n` +
    `  factory: function (require, module) {\n` +
    `'use strict'\n` +
    `${body}` +
    `  }\n` +
    `});\n`
  )
}

async function main() {
  const [coreSrc, hostSrc, clientSrc] = await Promise.all([
    read(SRC('core.js')),
    read(SRC('index.js')),
    read(SRC('client/index.js')),
  ])

  // Syntax gate before writing anything: compile the CJS factory body.
  // eslint-disable-next-line no-new-func
  new Function(buildClientBundle(coreSrc, clientSrc))

  const artifacts = new Map([
    [LIB('core.js'), BANNER + coreSrc],
    [LIB('index.js'), BANNER + hostSrc],
    [LIB('client.cjs'), buildClientBundle(coreSrc, clientSrc)],
  ])

  if (process.argv.includes('--check')) {
    let drift = false
    for (const [path, expected] of artifacts) {
      let actual = null
      try { actual = await readFile(path, 'utf8') } catch { /* missing counts as drift */ }
      if (actual !== expected) {
        console.error(`DRIFT: ${path} does not match sources (run: npm run build)`)
        drift = true
      }
    }
    if (drift) process.exit(1)
    console.log('build check OK: lib/ is in sync with src/')
    return
  }

  for (const [path, content] of artifacts) {
    await writeFile(path, content, 'utf8')
    console.log('wrote', path)
  }

  // Smoke: the host entry must import cleanly outside DSH (it has zero
  // runtime deps; optional host APIs are feature-detected inside apply()).
  await import(pathToFileURL(LIB('index.js')).href)
  console.log('host entry import smoke OK')
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
